### ISSUE TITLE
Add list types and values to Element, Substance, and Style

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#173] opened 2019-02-06 22:37 UTC
We are very soon going to need to support polymorphic lists in Element, Substance, and Style (both selector and block). This is necessary for the raytracing domain and for several subsequent ones (e.g. graph theory, neural networks). Here is an example usage in raytracing from the design paper:

![image](https://user-images.githubusercontent.com/2762356/52378352-710fb980-2a35-11e9-9fae-bfade706d481.png)
![image](https://user-images.githubusercontent.com/2762356/52378358-740aaa00-2a35-11e9-97b1-553b9d572665.png)

Specifically:
* Element needs to be able to parse, specify, typecheck, etc. lists (as a builtin polymorphic type that can be used to define further types)--with syntactic sugar
* Substance needs to be able to parse, specify, typecheck lists (as values of list types)--with syntactic sugar
* Style selectors need to be able to parse and match on those list types and lists of values from Substance
* Style blocks need to be able to specify lists of expressions and operate generically over them (this may be a task for a separate issue)

**Comment by hypotext** [comment] 2019-02-06 22:44
@dormaayan @wodeni Let's coordinate on doing this soon. I think lists should be added in Element and Substance before they're added in Style. I can deal with any Style semantics needed.

@dormaayan Does this sound like something you'd be interested in working on? I think we already have semantics in Element and Substance for type constructors, but I'm not clear on what we've implemented and what we haven't done yet. (I pasted in the lines from Fig. 22 of the design paper and they don't seem to parse.)

**Comment by dormaayan** [comment] 2019-02-07 05:50
@hypotext, I didn't implement  this yet (that's the only revision left in the language and we all agreed back than to wait until it's needed) but I'll happy to start work on that in the next few days.

**Comment by wodeni** [comment] 2019-02-07 15:23
@dormaayan Hapoy to help if needed, since I’ll be the one using it in raytracing very soon

**Comment by hypotext** [comment] 2019-02-07 17:22
@dormaayan Awesome, thanks!

**Comment by dormaayan** [comment] 2019-02-08 09:46
@hypotext 
We might have a problem with the the definition of lists:

In order ot define lists, we have to define 2 `vconstructor`s:

1. `vconstructor Nil ['X : type] : List('X)`
2. `vconstructor Cons ['X : type] (head : 'X , tail : List('X)) : List('X)`

These 2 `vconstructor`s are for the same type. Currently, my type checker doesn't allow that because of the deconstructors (we would like to access fields inside the `vconstructor` but if we have few of them, with different fields, this is not well-defined anymore)

The solutions that I can think of to hack that around involve making the deconstructor type checking depending on the used `vconstructor` but that doesn't look to me as a reasonable language design.

What do you think?

**Comment by dormaayan** [comment] 2019-02-08 15:45
Another option is to define a built-in type of lists which is not based on a recursive definition, but that's will avoid using these recursive building blocks in the future for other structures...

**Comment by hypotext** [comment] 2019-02-08 15:53
Yeah, if there are multiple possible ways to construct a value, then functional languages provide a way to discriminate between these branches and then deconstruct the value via pattern-matching (as you are already familiar with from Haskell etc):

```
f [] = -- do something
f (x:xs) = -- do something else
```

My thinking is that most of the time, people will not be defining sophisticated algebraic datatypes in Element. I think we should provide some built-in types and syntax that can be used in Element and Substance, such as 2-tuples and polymorphic singly-typed lists. Eventually, these types should compose, so e.g. you could have a list of tuples of some other types, but we can start with non-nested types.

**Comment by dormaayan** [comment] 2019-02-08 16:08
The problem is not in`Style` where you have pattern matching but in Substance in cases such as:
`In(x, f.domain)` where you access a field. 

But yes, let's not use the recursive definition and create for now 2 simple datatypes: a list and a tuple and see what else will be needed in the future

**Comment by hypotext** [comment] 2019-02-08 16:21
When I refer to pattern-matching, I'm talking about general pattern-matching in functional ML-like languages, not Style matching (understandable confusion, but what we're doing is not that kind of pattern-matching) :-) If we want to discriminate between branches of a list in *Substance* (i.e. Nil or Cons), then *Substance* needs its own kind of pattern-matching.

OK, I'm on board with the built-in datatypes. Can you let me know how you're planning to extend the  the syntax and semantics of Element/Substance with tuples and lists (i.e. constructing and deconstructing them)? It's a standard PL construct, but definitely worth spending time thinking through before going to the implementation stage. Books like Pierce's TAPL have chapters about this.

**Comment by dormaayan** [comment] 2019-02-14 07:02
@hypotext, @wodeni :

As we agreed (seems also Jonathan agree with that as well from the emails) it doesn't make sense to implement the `Nil & Cons` mechanism. The other option I thought about is making "built-in lists":

1. No definitions at the `Element` program
2.  At Substance, using a built-in syntax: `List(Type) list = [X1,...,Xn]`
3. The type-checking of a list will be simply assign`X1,...,Xn` with the type `Type` and declare them as vars
4. In addition, In the environment, to add all the relevant predicates (that will be in use at Style):
4.1. `InList(X1,list) ... InList(Xn,list)`
4.2 `Sublist([any sublist),list`

A similar strategy will be for pairs (except the element don't have to be of the same type)

In case we don't do the raytracing domain any time soon, I will be happy to do that in the future when relevant. If it is still urgent, let me know 😃

**Comment by wodeni** [comment] 2019-02-14 21:51
At the design level, I am wondering about (1) can the lists be polymorphic? and (2) do you plan to implement the syntax in the parser, or as some syntactic sugar? @hypotext may have more things about formalism?

At the implementation level, I think the list parser/checker will be reused by at least Substance, Style, and potentially the new View language. I wonder if we can somehow implement this in a more modular way.

**Comment by dormaayan** [comment] 2019-02-18 16:09
Most of the work on the Element\Substance side is done (I added built-in generic lists as described). The predicates should be implements but that's should be fairly easy.
Let me know when you decide regarding the Raytracing domain so I'll know when and how exactly to complete that.

**Comment by hypotext** [comment] 2019-02-18 19:10
Thanks @dormaayan! Can we also use lists in Element as a built-in type? e.g. `operator DoSomethingToList(x : List(Vertex)) : List(Vertex)`

**Comment by dormaayan** [comment] 2019-02-18 21:12
I'm still facing a few problems with these TypeVars (since we never used them before) but yeah, that's the plan

**Comment by hypotext** [comment] 2021-01-18 22:42
Bumping this issue as we need this feature by Feb 15 for our upcoming domain expert study. We will finally look at the PR...

**Closed** 2021-09-29 19:11 UTC
Labels: system:parser, system:language, kind:semantics
