### ISSUE TITLE
Does not work on Linux due to "recursive watch"

### ISSUE THREAD

**Issue by Dev380** [penrose/penrose#913] opened 2022-03-14 15:55 UTC
**Describe the bug**
A clear and concise description of what the bug is. If there is an error in the inspector pane, please paste that string in.

Using npm 16, or any version above 13, gives (with ``yarn start``):

```
@penrose/core: $ yarn build:parsers
@penrose/browser-ui: $ node build.js -w
@penrose/browser-ui:  > src/App.tsx:15:7: error: Could not resolve "@penrose/core" (mark it as external to exclude it from the bundle)
@penrose/browser-ui:     15 │ } from "@penrose/core";
@penrose/browser-ui:        ╵        ~~~~~~~~~~~~~~~
@penrose/browser-ui: serving ./public at http://localhost:3000/ (livereload on :13000)
@penrose/browser-ui:  > src/inspector/views/Errors.tsx:1:26: error: Could not resolve "@penrose/core" (mark it as external to exclude it from the bundle)
@penrose/browser-ui:     1 │ import { showError } from "@penrose/core";
@penrose/browser-ui:       ╵                           ~~~~~~~~~~~~~~~
@penrose/browser-ui:  > src/inspector/views/GraphUtils.ts:6:7: error: Could not resolve "@penrose/core" (mark it as external to exclude it from the bundle)
@penrose/browser-ui:     6 │ } from "@penrose/core";
@penrose/browser-ui:       ╵        ~~~~~~~~~~~~~~~
@penrose/browser-ui:  > src/inspector/makeViewBoxes.tsx:1:45: error: Could not resolve "@penrose/core" (mark it as external to exclude it from the bundle)
@penrose/browser-ui:     1 │ import { bBoxDims, RenderShape, Shape } from "@penrose/core";
@penrose/browser-ui:       ╵                                              ~~~~~~~~~~~~~~~
@penrose/browser-ui: Unhandled exception: TypeError: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
@penrose/browser-ui:     at new NodeError (node:internal/errors:371:5)
@penrose/browser-ui:     at Object.fs [as watch] (node:fs:2247:11)
@penrose/browser-ui:     at zb.watch (/home/alexander/penrose/node_modules/serve-http/src/livereload.js:158:20)
@penrose/browser-ui:     at nb.<anonymous> (/home/alexander/penrose/node_modules/serve-http/src/server.js:139:7)
@penrose/browser-ui:     at Object.onceWrapper (node:events:639:28)
@penrose/browser-ui:     at nb.emit (node:events:520:28)
@penrose/browser-ui:     at Server.emit (node:events:520:28)
@penrose/browser-ui:     at emitListeningNT (node:net:1364:10)
@penrose/browser-ui:     at processTicksAndRejections (node:internal/process/task_queues:82:21)
@penrose/core: $ nearleyc src/parser/Domain.ne > src/parser/DomainParser.ts && nearleyc src/parser/Substance.ne > src/parser/SubstanceParser.ts && nearleyc src/parser/Style.ne > src/parser/StyleParser.ts
@penrose/browser-ui: error Command failed with exit code 2.
@penrose/browser-ui: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run watch exited 2 in '@penrose/browser-ui'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
The tutorial says to run it again, however that does not work. A lower version does not recognize "rmSync" which is supposedly a feature added in node.js 14.
**To Reproduce**

1. Clone the repository, main branch, with git clone, on Linux (currently using Debian).
2. Cd into the directory, and do ``yarn && yarn start``
3. Wait until it exits with code 2.

**Expected behavior**
``yarn start`` correctly starts on Linux
**Desktop (please complete the following information if applicable):**

- OS: Debian 11

**Additional context**
I think this is due to a problem with node not supporting recursively watching directories on Linux. It seems like others have had this problem before:
https://stackoverflow.com/questions/43112227/recursive-node-js-fs-watch-on-linux#46513049
https://github.com/gmasmejean/watch-recursivly/blob/master/watch.js
https://github.com/nodejs/node/issues/36005

**Comment by samestep** [comment] 2022-03-21 15:33
Ah sorry I didn't get around to this yet; will take a look as soon as I can.

**Comment by samestep** [comment] 2022-03-23 17:30
Tried this just now and was able to reproduce. I also tried it on b9a90bc8b7bb303d1a86ca178cdfc03c3a4ed10f and got the same issue, so this has been around longer than I've been on the project :sweat_smile:

@wodeni any idea if there's a way we can fix this?

**Comment by wodeni** [comment] 2022-03-23 19:34
> Tried this just now and was able to reproduce. I also tried it on [b9a90bc](https://github.com/penrose/penrose/commit/b9a90bc8b7bb303d1a86ca178cdfc03c3a4ed10f) and got the same issue, so this has been around longer than I've been on the project 😅
> 
> @wodeni any idea if there's a way we can fix this?

@hsharriman had this problem before in #565 and we still have an open issue #552 unresolved, because we couldn't find a platform-independent Node engine version... 

For @Dev380's question, try __downgrading to v12__, which worked in #565.

**Comment by upsj** [comment] 2022-04-04 12:53
A workaround that partially disables the livereload functionality would be setting the `recursive` parameter to `false`, in my case replacing `this.watcher=rb.watch(a,{recursive:!0}` by `this.watcher=rb.watch(a,{recursive:!!0}` in `node_modules/serve-http/serve-http.js`

**Comment by marcusps** [comment] 2022-04-18 15:31
I wanted to try Penrose on Linux and came across this issue (Ubuntu 21.10).  It does not look like `node` will improve recursive watch support on Linux any time soon, and expect the issue to be fixed in `libuv`, but it does not look like the issue will be addressed by `libuv` either.  

One way to address these problems would be to use `chokidar` ([link](https://www.npmjs.com/package/chokidar)) which supports recursive watch on all platforms -- but that may require more substantial changes and to add a dependency.

**Comment by samestep** [comment] 2022-04-19 19:32
@wodeni Just to confirm, does #929 resolve this?

**Comment by wodeni** [comment] 2022-04-19 19:41
> @wodeni Just to confirm, does #929 resolve this?

Yep that's the goal. Still need to see if vite will work reliable for linux obviously

**Closed** 2022-04-26 20:18 UTC
Labels: kind:external-bug

**Comment by wodeni** [comment] 2022-04-26 21:08
Thanks all for commenting on this issue!

In #929, we removed `serve-http` and switched to [vite](https://vitejs.dev/) for live-reload mode for both `@penrose/browser-ui` and `@penrose/panels`. To try it out:

* Pull from `main`
* Run `yarn clean`
* Follow the [Building and Running page](https://github.com/penrose/penrose/wiki/Building-and-running) instructions again

Let us know if you run into this issue again. If so, we'll reopen this issue and investigate.
