### ISSUE TITLE
clean up Style/Sub/DSL programs in working examples

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#572] opened 2021-05-26 20:16 UTC
People often look to them for examples, but they have a lot of random testing code (e.g. parsers) which makes them not good as illustrative examples. Also add comments saying what the code is doing.

**Comment by wodeni** [comment] 2023-08-01 19:55
Closing because the issue is a bit too vague.

**Closed by wodeni** 2023-08-01 19:55 UTC
Labels: kind:documentation, kind:example, context:domain-expert-study, priority:high
