### ISSUE TITLE
Layering commands only work in one direction for PoincareDisk.sty in [hyperbolic] branch

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#433] opened 2020-12-16 19:31 UTC
This works:

```
   layer p.dotShape above g.shape
   layer q.dotShape above g.shape
```

But this doesn't!

```
   layer g.shape below p.dotShape
   layer g.shape below q.dotShape
```

**Comment by wodeni** [comment] 2020-12-16 23:09
This is caused by https://github.com/penrose/penrose/blame/master/src/Penrose/Style.hs#L586. Fixed by 4d60331

**Closed by wodeni** 2020-12-16 23:09 UTC
Labels: bug, graphics, style
