### ISSUE TITLE
Something broke with the optimizer since last Penrose week

### ISSUE THREAD

**Issue by GeometryCollective** [penrose/penrose#982] opened 2022-05-17 21:59 UTC
A bunch of examples, like those in `triangle-mesh-2d`, no longer work.  The optimizer gets stuck for most seeds, and can't make any progress.

I tried creating a minimal example that reproduces this behavior.  Here's a minimal-ish triple (I'm just putting the source directly in the GitHub issue, rather than making a whole branch that pollutes our history…):

[minimal-example.dsl.txt](https://github.com/penrose/penrose/files/8711792/minimal-example.dsl.txt)
[minimal-example.sty.txt](https://github.com/penrose/penrose/files/8711793/minimal-example.sty.txt)
[minimal-example.sub.txt](https://github.com/penrose/penrose/files/8711794/minimal-example.sub.txt)

**Comment by samestep** [comment] 2022-05-18 01:45
I haven't looked closely at this yet (will tomorrow) but one important takeaway from this is that if someone cares about an example, they should really put it in the [registry](https://github.com/penrose/penrose/wiki/Registry). Our determinism check on the registry in CI is very powerful, and @wodeni and I put a lot of effort into making sure we don't break registry diagrams when refactoring, but it is far more difficult for us to catch errors in trios that don't appear in the registry.

**Comment by keenancrane** [comment] 2022-05-18 02:18
@samestep Can you make a wiki page about what the registry is and how to add examples?

In this case it seems like a symptom of a deeper issue (not just a quirk of a particular domain), since the example is extremely simple: a dot with a label.

**Comment by samestep** [comment] 2022-05-18 02:29
@keenancrane My message above links to that wiki page.

**Comment by keenancrane** [comment] 2022-05-18 02:31
Mea culpa. Thank you @samestep.

**Comment by samestep** [comment] 2022-05-18 11:45
> Mea culpa. Thank you @samestep.

@keenancrane No worries!

> In this case it seems like a symptom of a deeper issue (not just a quirk of a particular domain), since the example is extremely simple: a dot with a label.

Right, I think I phrased my earlier message a bit poorly. What I meant to say is that we place a nontrivial amount of reliance on the registry for regression testing, so it's important that we have a diverse set of diagrams in the registry. It's hard to predict ahead of time what "diverse" should mean, so in my opinion a good policy is that if you create a new diagram in `@penrose/examples`, you should default to adding it to the registry _unless_ there's a specific good reason not to.

**Comment by samestep** [comment] 2022-05-18 13:13
Is `CorbeauYak479` an example of a variation where it gets stuck, as you mentioned?

**Comment by samestep** [comment] 2023-02-28 15:18
Closing this since it's unclear whether something broke or, if so, what.

**Closed** 2023-02-28 15:18 UTC
Labels: kind:bug, priority:high, layout
