### ISSUE TITLE
Sending image aspect ratio to backend

### ISSUE THREAD

**Issue by miyehn** [penrose/penrose#208] opened 2019-04-19 20:19 UTC
@maxkrieger @wodeni Currently the backend doesn't know the image file's aspect ratio, so although we can set a target aspect ratio for image or optimize its width and hight, there's no way to "keep the original aspect ratio of an image".
Looks like image files are loaded from front end. Is it possible to send its aspect ratio (or its original dimension) to back end when loading images? If so, could you direct me to where should I change in the code to get this information? Thanks!

**Comment by hypotext** [comment] 2019-04-19 23:13
I looked into this and it seems like the right way to go is to load the image asynchronously first (this [SO answer](https://stackoverflow.com/a/51063852/7342065) has a useful code snippet), put the element in a `rendered` property of the shape in the frontend, then get its dimensions and set the transform in `ImageTransform.tsx`. We can treat them similarly to labels.

Side note, I also need the image dimensions in the frontend so that I can render the image appropriately (i.e. not flipped vertically). This is because I need to perform a vertical flip about the origin in the beginning, and doing this operation about the origin requires doing a translation that involves the image dimensions.

**Comment by maxkrieger** [comment] 2019-04-19 23:27
Yeah that's what my approach would be. We can send image dimensions in an
update packet, just make sure to make the "update" message schema match
accordingly. Same exact idea as Labels.

**Comment by hypotext** [comment] 2019-04-20 19:20
Ok, I'll do this today then

**Comment by hypotext** [comment] 2019-04-20 22:31
@miyehn @maxkrieger I think my most recent commit resolves this issue. Can you two review to make sure?

@miyehn I replaced the length properties of an image by the initial dimensions and the scaling properties. Feel free to add length back if you want.

**Comment by wodeni** [comment] 2019-04-20 23:41
I checked out `transforms` and tried to build it, but got an error about `libiconv` from the linker (similar to this: https://github.com/commercialhaskell/stack/issues/825).

**Comment by maxkrieger** [comment] 2019-04-21 00:17
Can confirm the hmatrix dep was problematic on my machine too at a low level, got a different error: `/lib/liblapack.a(dgesvd.f.o): undefined reference to symbol '_gfortran_concat_string@@GFORTRAN_7'`

**Comment by maxkrieger** [comment] 2019-04-21 00:32
Can't do docker either -- does it work on @miyehn's machine?

**Comment by miyehn** [comment] 2019-04-21 14:55
@maxkrieger I just pulled and it worked well for me? I could also use Newton's method to optimize objectives.

**Comment by hypotext** [comment] 2019-04-21 19:49
@wodeni @maxkrieger Hm, that's strange. Does doing `stack install [--profile] hmatrix` or `cabal install hmatrix` first work?

**Comment by maxkrieger** [comment] 2019-04-23 21:51
WFM in *isolated* Docker after running `stack clean`. @wodeni it's definitely your machine!

**Comment by wodeni** [comment] 2019-04-24 22:11
> WFM in _isolated_ Docker after pulling and running `stack clean`. @wodeni it's definitely your machine!

Gotcha. I'll try that. Thanks!

**Comment by wodeni** [comment] 2019-05-29 15:56
This `iconv` issue came back recently on my machine. The root cause of this is duplicated `libiconv.dylib` files. macOS has its own libiconv, but somehow I have another version installed by HomeBrew. Removing the `.a` and `.dylib` files from `/opt/local/lib/` eventually solved my problem. I found these duplicated files by running `mdfind libiconv`. I hope nobody runs into this ever again tho!

**Comment by wodeni** [comment] 2021-09-29 19:19
Not sure if this is still needed. Closing for now and collected to #653

**Closed by wodeni** 2021-09-29 19:19 UTC
Labels: kind:graphics
