### ISSUE TITLE
local vars don't appear to be fully substituted out in translation

### ISSUE THREAD

**Issue by k-qy** [penrose/penrose#523] opened 2021-03-10 18:11 UTC
Cases:

* https://github.com/penrose/penrose/pull/522#discussion_r591015240
* In namespaces, referring to something like `canvas.box` as `box` doesn't work

Cause of case 1: `substituteBlockExpr` should substitute in `GPIDecl` case, into the `PropertyDecl`s' values as well. It is currently written to do so -- not sure why this fails?

Cause of case 2: ???

**Comment by hypotext** [comment] 2021-03-13 02:24
Hey @wodeni, I was not able to repro the LocalVar thing you pointed out here: https://github.com/penrose/penrose/pull/522#discussion_r591015240 

When I have local vars in a polygon path, as in the third example in #513, I only see FieldPaths:

![image](https://user-images.githubusercontent.com/2762356/111015921-0e5a1c00-8379-11eb-8a53-14515bfe2cc2.png)

See commit e82fdef7c994f6faf84d642a864273c64d02fc42, running `roger watch shapes.sub shape-spec.sty shape-spec.dsl`.

One potential issue is that Will should be using lists of points, not vector syntax:

`points: [(x1,y1), (x2,y2), (x3,y3)]` not `points: ((x1,y1), (x2,y2), (x3,y3))`

However, with either version, I don't see any stray LocalVars.

Can you push a reproducible example of the bug to `polygon-debug`?

**Comment by wodeni** [comment] 2021-03-13 03:01
Good point about vector vs. list of vectors, but I think either way should work, assuming the shapedef is correct. Actually it would be good to check what's going to happen if the shapedef doesn't really match with the style values. 

Anyway, here's the state after running the latter version:
![image](https://user-images.githubusercontent.com/11740102/111016918-73fcd700-837e-11eb-9220-e9f3e3db76c1.png)

**Comment by wodeni** [comment] 2021-03-13 03:08
Also, maybe try printing out values or use `download state` button instead of relying on the inspector. I'm not 100% sure about it's lifecycle

**Comment by hypotext** [comment] 2021-03-13 03:28
Ok, I'm on your commit and I see some `LocalVar`s in the downloaded state. https://gist.github.com/hypotext/79a6eaed40ced236ddd3c987d76f6f32

But when I print the state in `stepState` (see latest commit), in the console for the last state printed during optimization, I see only `FieldPath`s. 

![image](https://user-images.githubusercontent.com/2762356/111017450-ac51e480-8381-11eb-8030-ef7ebaf39767.png)

So, I'm still not able to repro.

Any ideas about what could cause the Inspector/console version of the state to show a translation with `FieldPath`s, whereas the downloaded state looks different? This suggests it's not purely a Style compiler problem, but maybe caused by something else (`prepareState` or some other version of the state that is the downloaded version)? It would be helpful to know at what point in the app lifecycle the `LocalVars` are present.

**Comment by samestep** [comment] 2022-08-16 20:27
Is this still an issue? Particularly after #984?

**Comment by samestep** [comment] 2022-08-19 21:28
I'm closing this; feel free to reopen if I'm mistaken.

**Closed by samestep** 2022-08-19 21:28 UTC
Labels: kind:bug, system:style
